name: Spring Boot CI

on:
  push:
    branches: [main, staging, production]
  pull_request:
    branches: [main, staging, production]

jobs:
  build:
    name: Build, Test y Calidad Código
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Revisar dependencias
        run: ./gradlew dependencies

      - name: Compilar proyecto
        run: ./gradlew bootJar